module.exports = {
    someSidebar: {
        Info: ["home", "laws", "security"],
        "Content Type": [
            "cartoons-and-anime",
            "comics-and-manga",
            "books-and-magazines",
            "academic-papers-and-textbook",
            "courses-and-tutorials",
            "documentaries",
            "audiobooks",
            "music-and-podcasts",
            "movies-and-tv-shows",
            "sports",
            "games",
            "software",
            "creative-assets",
            "iptv",
        ],
        Sources: [
            "torrents",
            "usenet",
            "direct-downloads",
            "discord",
            "irc",
            "telegram",
            "dc-plus-plus",
        ],
        Miscellaneous: [
            "browser-extensions",
            "userscripts",
            "bypass-paywalls",
            "file-sharing",
            "cloud-storage",
            "media-centre-applications",
            "misc",
            "dead",
        ],
    },
};
